# -*- coding: utf-8 -*-
"""python_sets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R9QEhTacBi3SRlN4H1kzQ_3qnVW0XCt4

# Cunjuntos (Sets)

Los conjuntos en python son una estructura para guardar datos, o colecciones de datos, únicos. Es decir, **no se admiten elementos duplicados.**
Un ejemplo de esto son lo identificadores de los estudiantes, ids de usuarios de una plataforma, etc.
"""

# Ejemplo 1: Creación de un conjuntos

# Conjunto de números enteros:
id_estudiantes = {112, 114, 116, 118, 115}
print('IDs estudiantes:', id_estudiantes)

# Conjunto de caracteres:
vocales = {'a', 'e', 'i', 'o', 'u'}
print('Conjunto de vocales:', vocales)

# Conjunto de datos mixtos:
conjunto_mixto = {'Hello', 101, -2, 'Bye'}
print('Conjunto de datos mixtos:', conjunto_mixto)

# Ejemplo 2: Creación de un conjunto con el constructor set()
conjunto_vacio = set()
print('Conjunto vacío:', conjunto_vacio)

# Ejemplo 5: convertir conjunto en tupla
conjunto = {1, 2, 3, 4, 5}
tupla = tuple(conjunto)
print('Tupla a partir de un conjunto:', tupla)

# Ejemplo 6: convertir conjunto en lista
conjunto = {1, 2, 3, 4, 5}
lista = list(conjunto)
print('Lista a partir de un conjunto:', lista)

# Ejemplo 3: Convertir lista en conjunto
lista_numeros = [1, 2, 3, 4, 5, 5, 4]
conjunto_numeros = set(lista_numeros)
print('Conjunto de números a partir de una lista:', conjunto_numeros)

# Ejemplo 4: convertir tupla en conjunto
tupla = (1, 2, 3, 4, 5, 5, 4)
conjunto_numeros = set(tupla)
print('Conjunto de números a partir de una tupla:', conjunto_numeros)

# Ejemplo 7: Creación de un conjunto a partir de una cadena
cadena = 'Hola mundo'
conjunto_caracteres = set(cadena)
print('Conjunto de caracteres a partir de una cadena:', conjunto_caracteres)

# Ejemplo 8: Eliminar elementos duplicados de conjunto
conjunto = {1, 2, 3, 4, 5, 2, 5}
print(conjunto)

# Ejemplo 9: eliminar elementos duplicados de una lista
lista = [1, 2, 3, 4, 5, 5, 4]
conjunto = set(lista)
lista = list(conjunto)
print(lista)

# Ejemplo 10: eliminar elementos duplicados de una tupla
tupla = (1, 2, 3, 4, 5, 5, 4)
conjunto = set(tupla)
tupla = tuple(conjunto)
print(tupla)

# Ejemplo 11: eliminar elementos duplicados de una cadena
cadena = 'Hola mundo'
conjunto = set(cadena)
cadena = ''.join(conjunto)
print(cadena)

# Ejemplo 12: mostrar métodos de los conjuntos
conjunto = set
dir(conjunto)

# Ejemplo 13: Operaciones de conjuntos (Métodos de conjuntos)
# Sean los conjuntos
conjunto1 = {1, 2, 3, 4, 5}
conjunto2 = {4, 5, 6, 7, 8}

print("Conjunto1:", conjunto1)
print("Conjunto2:", conjunto2)

# Unión de conjuntos
union = conjunto1 | conjunto2
print("Unión de conjuntos:", union)

# Intersección de conjuntos
interseccion = conjunto1 & conjunto2
print("Intersección de conjuntos:", interseccion)

# Ejemplo 14: Diferencia de conjuntos:
# Diferencia de conjuntos
diferencia = conjunto1 - conjunto2
print("Diferencia de conjuntos (conjunto1 - conjunto2):", diferencia)

# Diferencia simétrica de conjuntos
diferencia_simetrica = conjunto1 ^ conjunto2
print("Diferencia simétrica de conjuntos:", diferencia_simetrica)

# Ejemplo 15: Verificaciones en conjuntos:
# Verificar si un conjunto es subconjunto de otro
es_subconjunto = conjunto1.issubset(conjunto2)
print("¿conjunto1 es subconjunto de conjunto2?:", es_subconjunto)

# Verificar si un conjunto es superconjunto de otro
es_superconjunto = conjunto1.issuperset(conjunto2)
print("¿conjunto1 es superconjunto de conjunto2?:", es_superconjunto)

# Ejemplo 16: Uso de los métodos añadir, remover, verificar, longitud, limpiar

# Agregar un elemento a un conjunto
conjunto1.add(6)
print("Conjunto1 después de agregar el elemento 6:", conjunto1)

# Eliminar un elemento de un conjunto
conjunto1.remove(6)
print("Conjunto1 después de eliminar el elemento 6:", conjunto1)

# Verificar si un elemento está presente en un conjunto
esta_presente = 3 in conjunto1
print("¿El elemento 3 está presente en conjunto1?:", esta_presente)

# Obtener la longitud de un conjunto
longitud = len(conjunto1)
print("Longitud de conjunto1:", longitud)

# Limpiar un conjunto (eliminar todos los elementos)
conjunto1.clear()
print("Conjunto1 después de limpiar:", conjunto1)

# Ejemplo 17: iterar sobre un conjunto
conjunto = {1, 2, 3, 4, 5}
for elemento in conjunto:
    print(elemento)

